name: Release legacy-v3
on:
  workflow_dispatch:
env:
  GIT_AUTHOR_EMAIL: ${{ secrets.BOT_EMAIL }}
  GIT_AUTHOR_NAME: ${{ secrets.BOT_NAME }}
  GIT_COMMITTER_EMAIL: ${{ secrets.BOT_EMAIL }}
  GIT_COMMITTER_NAME: ${{ secrets.BOT_NAME }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'legacy-v3'

      - uses: actions/setup-node@v4
        with:
          node-version: node
          registry-url: 'https://registry.npmjs.org'

      - run: |
          npm ci
          npm run build
          npm version patch

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: git push
